image: instantsolutions/gitlab-ci-android-runner:latest

before_script:
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - echo y | chmod +x ./gradlew

stages:
  - build
  - test

build:
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
    - ./gradlew test --info
